---
- name: test plybook
  hosts: all
  become: yes
  tasks:
  - name: creating multiple users
    user: name='{{item}}' state=present
    with_items: 
        - raj
        - rekha
        - dugu
        - agstya
