---
- name: test playbook
  hosts: all
  become: yes
  tasks:
  - name: installed httpd package
    yum:
      name: httpd
      state: present
  - name: statrt httpd service
    service: 
      name: httpd
      state: started
