---
# tasks file for setup-apache-roles
- name: install httpd 
  yum:
    name: httpd
    state: installed
  notify: start httpd
  when: ansible_os_family == 'RedHat'

- name: install apache2
  yum:
    name: apache2
    state: present
  notify: start apache2
  when: ansible_os_family == 'Debian'

- name: copy index.html
  copy:
    scr: /home/deepika/playbooks/index.html
    dest: /var/www/html
    mode: 0666    
